version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: attrition_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/frontend/node_modules
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    container_name: attrition_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge